### ISSUE TITLE
Defunct as of 2024-10-08

### ISSUE THREAD

**Issue by ulysses4ever** [andreasabel/fix-whitespace-action#4]
Here's an example of failed run: https://github.com/haskell/cabal/actions/runs/11235927069/job/31234930655?pr=10435#step:3:39

**Comment by andreasabel** [comment]
I hope I fixed this in `v1.3.1`.  Please let me know whether it is fixed.

**Comment by ulysses4ever** [comment]
The folks already switched to a makefile target that does all the job, so I don't have an easy way to check it anymore, I'm sorry. I trust that it works!
